### ISSUE TITLE
Ezekiah Grimme bugs

### ISSUE THREAD

**Issue by J0eJames** [J0eJames/Doomtown-Reloaded-OCTGN#32]
Let me know if this should be 3 separate issues:

Bug 1) When using Grimmes Noon Boot ability, if you successfully find a spell and attach it to a dude, it attaches flipped over (the back of the card shows instead of the front).

Bug 2) When using General Store to reduce the cost of a miracle, it is not costed correctly if there are other copies of the spell and you have Grimme (sounds like general store applies the discount, then Grimme increases cost, instead of the other way around).  This reported by DirkPortly on Discord

Enhancement request:  When using Grimmes Noon Boot ability, it would be super nice to list the 5 cards that were shown in the log, as they are revealed and both players get a chance to see what they were.

**Comment by mmeldo** [comment]
Bug 1 and Enhancement request are quite easy to do, but Bug 2 will be little more complicated as it is with any multiple reductions (e.g. Morgan Stables + Maggie)

**Comment by J0eJames** [comment]
Yeah, let's ignore bug 2 for now, thanks

**Comment by mmeldo** [comment]
There is another bug related to Ezekiah Grimme. It increases cost also for conditions and other goods in case there are copies in play.
