### ISSUE TITLE
Inner Struggle/Tse-Che-Nako's Weaving

### ISSUE THREAD

**Issue by RSDoom** [J0eJames/Doomtown-Reloaded-OCTGN#8]
Forgot some small script queries with the recent OCTGN I played last over the weekend. Inner Struggle was not attaching correctly but otherwise worked okay.
Tse-Che-Nako's Weaving makes the pull but otherwise does not seem to run.

Thank you!

**Comment by mmeldo** [comment]
I will put Tse-Che-Nako's Weaving into different issue as it can be completed once I am done with the feature that introduces adjacency. Also, even though it makes the pull, it checks it against 6 and not 7.
New issue #9

**Comment by mmeldo** [comment]
Can you please check again if the Inner Struggle does not attach correctly? I tried and it works fine. Either you target opponent's home before playing and it will attach there, or it will give you list of hosts (which are all dudes, deeds and outfits, but that is not a big problem I guess)

**Comment by mmeldo** [comment]
Probably was accidentally fixed by some other update.
